### ISSUE TITLE
BUFFER_SIZE

### ISSUE THREAD

**Issue by akostrik** [pasqualerossi/42-School-Exam-Rank-03#10]
The subject tells "BUFFER_SIZE=xx, which has to be used as the buffer size for the read calls", but you use 10000 as the fixed size of the buffer. Is it authorized at the exam ?

**Comment by pasqualerossi** [comment]
It was at the time, but I'm not sure now though?

**Comment by abuonom** [comment]
Hi Pasquale, I'm at 42Roma and currently this code doesn't work, but we don't know why, let's assume it's for this buffersize

**Comment by pasqualerossi** [comment]
Let me know what the code is and I’ll update the repo.
