### ISSUE TITLE
the signature of the function in the ft_printf.c repo is not correct 

### ISSUE THREAD

**Issue by dabi-rac** [pasqualerossi/42-School-Exam-Rank-03#15]
Line 26 shows this:

    -int	  ft_printf(const char *format, ...)

but is not correct, as it should be 

    -int	  ft_printf(const char *format, ... )

with a space also AFTER the three dots.

I know it could be a small problem, even if your readme shows the real signature from the subject, but in the repo its wrong, and  this wrong version also works in the 42 grademe program https://grademe.fr/  so its really a hidden error.

It is frustrating because today I gave the exam, and It would not specify that the problem was in the signature of the function, as it would show traces listing the tests so it made solving the issue really confusing.

As always, reading the subject in the minute details would have saved me and other from this frustrating situation, hope this helps a bit other students!

**Comment by pasqualerossi** [comment]
create a pull request and I'll update it. Thanks!

**Comment by mgimon** [comment]
I just did the exam and I might have had the same problem. I failed, the trace showed me a bunch of tests but I couldn't find the problem. All my code was identical to the one in this repository, **which works in grademe.fr**.

My declaration signature was: 
```
int     ft_printf(const char *format, ...)
```
So it might have been the same problem that dabi-rac mentions. I can't be sure, though.

**Comment by pasqualerossi** [comment]
Updated. Thanks for noticing that!
