### ISSUE TITLE
ft_printf printing - in incorrect place

### ISSUE THREAD

**Issue by zakaria-mourtaban** [pasqualerossi/42-School-Exam-Rank-03#25]
<--------------~-~-~-~-~-~-~-~-~------------>
Simple test$
--Format---$
0$
42$
1$
5454$
2147483647$
-2147483648$
-2147483648$
2147483647$
$
0$
2a$
1$
154e$
7fffffff$
80000000$
80000000$
7fffffff$
ffffffff$
$
$
toto$
wiurwuyrhwrywuier$
(null)$
--toto-wiurwuyrhwrywuier-(null)-$
$
--Mixed---$
00422a21474836477fffffff-214748364880000000$
-0-0-42-2a-2147483647-7fffffff--2147483648-80000000-$
$
totowiurwuyrhwrywuier(null)$
--toto-wiurwuyrhwrywuier-(null)-$
written: 376$
\n
<--------------~-~-~-~-~-~-~-~-~------------>\n\n
<--------------~-~-~-~-~-~-~-~-~------------>
Simple test$
--Format---$
0d$
42d$
1d$
5454d$
2147483647d$
<--------------~-~-~-~-~-~-~-~-~------------>

this is the trace of 42-exam on the latest version of printf.
i wrote a version that passes the tester
#include <stdarg.h>
#include <stdlib.h>
#include <unistd.h>

int	putstr(char *str)
{
	int	i;

	i = 0;
	if (str == NULL)
		return (write(1, "(null)", 6));
	while (str[i] != '\0')
	{
		write(1, &str[i], 1);
		i++;
	}
	return (i);
}

int	putdigit(int num, int base)
{
	char	*b;
	int		len;

	len = 0;
	b = "0123456789abcdef";
	if (num < 0)
	{
		write(1, "-", 1);
		num *= -1;
		len++;
	}
	if (num / base == 0)
		return (write(1, &b[num % base], 1) + len);
	return (putdigit(num / base, base) + putdigit(num % base, base) + len);
}

int	ft_printf(const char *input, ...)
{
	int i;
	int len;
	va_list args;

	len = 0;
	i = 0;

	va_start(args, input);
	while (input[i] != '\0')
	{
		if (input[i] == '%' && input[i + 1] == 's')
			len += putstr(va_arg(args, char *));
		else if (input[i] == '%' && input[i + 1] == 'd')
			len += putdigit(va_arg(args, int), 10);
		else if (input[i] == '%' && input[i + 1] == 'x')
			len += putdigit(va_arg(args, int), 16);
		else
			len += write(1, &input[i], 1);
		i++;
	}
	va_end(args);
	return (len);
}

please check if this is an issue with the print f you wrote or the tester i am using

**Comment by YS8610** [comment]
Thanks for reporting this error. I have corrected the error and tested it on both printfTester and grademe tester. You can look at my pull request for the new code or wait for the pull request to be merged
