### ISSUE TITLE
Current commit for get_next_line won't pass the exam

### ISSUE THREAD

**Issue by alx-sch** [pasqualerossi/42-School-Exam-Rank-03#27]
- No static variable in the current approach at all → this will not work.
- Moulinette tests the amount of memory allocated for the retrieved line → hardcoding this to a large random number will fail.

**Comment by pasqualerossi** [comment]
Create a pull request and I’ll update the code.

**Comment by alx-sch** [comment]
fixed bz reverting to prev commit
