### ISSUE TITLE
Get_next_line not working

### ISSUE THREAD

**Issue by NaomiH42** [pasqualerossi/42-School-Exam-Rank-03#3]
Hello, your get_next_line solution is not working for us in the Exam rank 03 at 42 Prague.

**Comment by chmadran** [comment]
Hello, not working in  42 Paris either.

**Comment by pasqualerossi** [comment]
If you have another way to write get_next_line, let me know and I can add it to this Github Repo.

**Comment by mdabir1203** [comment]
I passed 4 days ago. This works completely fine and you can add this if you want to. I tried a lot of versions and finally I made this simpler one :) 
https://github.com/mdabir1203/42_Exam_Concepts/blob/main/Exam_Rank_03/get_next_line/get_next_line.c

**Comment by Zekao** [comment]
Skill issue, learn how to make exams by yourself ;)

**Comment by gkgy147** [comment]
This solution doesnt work on exam, moulinette throws error saying BUFFER_SIZE is not used.
