### ISSUE TITLE
leaks in the code you provide

### ISSUE THREAD

**Issue by Paghe** [pasqualerossi/42-School-Exam-Rank-03#8]
#include <stdlib.h>
#include <unistd.h>

char	*get_next_line(int fd)
{
    int i = 0;
    int rd = 0;
    char character;

    if (BUFFER_SIZE <= 0) 
        return (NULL);
	char *buffer = malloc(100000);  // check before the current BUFFER_SIZE and then malloc
    while ((rd = read(fd, &character, BUFFER_SIZE - BUFFER_SIZE + 1)) > 0)
    {
        buffer[i++] = character;    
        if (character == '\n')     
            break;                  
    }
    buffer[i] = '\0';             
    if (rd == -1 || i == 0 || (!buffer[i - 1] && !rd))
        return (free(buffer), NULL); 
    return (buffer);
}

**Comment by pasqualerossi** [comment]
What should the code look like to fix this problem?

**Comment by Paghe** [comment]
#include <stdlib.h>
#include <unistd.h>
char *get_next_line(int fd)
{
int i = 0;
int rd = 0;
char character;

if (BUFFER_SIZE <= 0) 
    return (NULL);
char *buffer = malloc(100000);  // check before the current BUFFER_SIZE and then malloc
while ((rd = read(fd, &character, BUFFER_SIZE - BUFFER_SIZE + 1)) > 0)
{
    buffer[i++] = character;    
    if (character == '\n')     
        break;                  
}
buffer[i] = '\0';             
if (rd == -1 || i == 0 || (!buffer[i - 1] && !rd))
    return (free(buffer), NULL); 
return (buffer);
}
check buffer_size and then malloc, i tried with the tester and is working. Without switching those lines traces's tester gives leaks

**Comment by kurz-m** [comment]
Either do it like Paghe is saying or do it as following:

```
#include <unistd.h>
#include <stdlib.h>

char	*get_next_line(int fd)
{
	int		i = 0;
	int		rd = 0;
	char	letter;
	char	*buffer = malloc(100000);

	if (BUFFER_SIZE <= 0)
		return (free(buffer), NULL); // add this free command --> seems like that it is not needed if you are doing it on Linux (does not give an error here)
	while ((rd = read(fd, &letter, BUFFER_SIZE - BUFFER_SIZE + 1)) > 0)
	{
		buffer[i++] = letter;
		if (letter == '\n')
			break;
	}
	buffer[i] = '\0';
	if (rd == -1 || i == 0 || (buffer[i - 1] == '\0' && rd == 0))
		return (free(buffer), NULL);
	return (buffer);
}
```
