### ISSUE TITLE
This code does not work for GNL new instructions (Rome 42 campus, since May 2023)

### ISSUE THREAD

**Issue by FrancoisCardinaud** [pasqualerossi/42-School-Exam-Rank-03#9]
Here are the new instructions for get_next_line in the rank 03 exam at 42 Rome:

"- What we call a "line that has been read" is a succession of 0 to n characters that end with '\n' (ascii code 0x0a) or with End Of File (EOF).

- '\n' should be included if there is one

- When you've reached the EOF, you must store the current buffer in a char * and return it.

- If the buffer is empty you must return NULL.

- In case of error, you must return NULL.

- In case of not returning NULL, the pointer should be free-able.

**- Your program will be compiled with the flag -D BUFFER_SIZE=xx, which has to be used as the buffer size for the read calls in your functions.**

- Your program can be compiled with AND without the -D flag

- Your function must be memory leak free

- When you've reached the EOF, your function should keep 0 memory allocated with malloc, except the line that has been returned.

- Calling your function get_next_line in a loop will therefore allow you to read the text available on a file descriptor one line at a time until the end of the text, no matter the size or either the text or one of its lines

- Make sure that your function behaves well when it reads from a file, from the standard output, from a redirection, etc...

- No call to another function will be done on the file descriptor between 2 calls of get_next_line.

- We consider that get_next_line has an undefined behavior when reading from a binary file." 

The instruction in **bold** is new compared to this current version. 
Unfortunately, even after implementing a ifndef in the .h file in order to accommodate this new rule, the exam is consistently failed. 
Some classmates have suggested that BUFFER_SIZE cannot be modified. Perhaps this can be a clue in solving why we are currently unable to pass this exam with the new rules?

Thanks a lot!

**Comment by gkgy147** [comment]
Same here in 42Bangkok also, even after defining buffersize in the .h, dont know why!!

**Comment by pasqualerossi** [comment]
What should the code look like now, share the code and I will update this repo with it.

**Comment by FunghiFannoBene** [comment]
#ifdef BUFFER_SIZE
#undef BUFFER_SIZE
#endif

#define BUFFER_SIZE 1

**Comment by 4fatty4** [comment]
I can confirm in 42 Paris code doesn't work too
